# Welcome to Jekyll!
#
# jekyll config docs:
# https://jekyllrb.com/docs/configuration/default/
# see also beautiful-jekyll-theme settings below.

title: notkeepingitreal.com
subtitle: software, business, and other business
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a technology blog by Kevin Burnett discussing software development,
  ruby, python, and business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://notkeepingitreal.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kbbkkbbk
github_username:  burnettk
permalink: /articles/:year/:month/:day/:title/
category_dir: articles/category
# https://feedburner.google.com/manage/td4d32kp82m2b3dvlr8qjjib34

include: [".htaccess", "tabs"]

# Build settings
# theme: minima
theme: beautiful-jekyll-theme
plugins:
  - jekyll-feed


# beautiful-jekyll-theme settings under here. maybe some are generic jekyll, but found them at:
# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml
navbar-links:
  About: "about"
author: Kevin Burnett

social-network-links:
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: burnettk
  twitter: kbbkkbbk
  youtube: "@kevinmburnett"

rss-description: Business blog on software development, ruby, python, and business.
